### ISSUE TITLE
Replacing source and destination language for migration direction

### ISSUE THREAD

**Issue by apragsdale** [grahamgower/demes#1]
As we talked about on the call and have run into this issue plenty of times before, `source` and `dest` are interpreted differently if you look forward in time vs backward (individuals migrating from/to vs lineages moving to/from, resp.). We could use unambiguous terms along the lines of `parental_deme` and `child_deme` instead, which would mean that interpretation doesn't swap around if we switch the direction of time in the model. Like `ancestor`, the parent/child interpretation is clear in both contexts. If we can avoid touching source/dest language entirely, that would be great.

I'd like to give a shot at supporting both forward- and backward-in-time constructions of demographies, with methods that automatically convert between the two. It's a bit of work, yes, but it's not clear to me how much work it would be until giving it a try. Having clear language about relationships and migration directions will help a lot to avoid confusing ourselves in the conversion as well.

What are your thoughts about `parental_deme` and `child_deme`, or any alternatives that you suggest?

cc: @molpopgen @jeromekelleher

**Comment by molpopgen** [comment]
I like that terminology.  We could also consider ancestor/descendant here, too, `ancestral_deme`  and `descendant_deme`, as `ancestor` is being used elsewhere?

**Comment by grahamgower** [comment]
These are really good suggestions. I like that they're more explicit about the biological relationship. There's a tradeoff here with the verbosity of appending `_deme` to these terms, and the succinctness of leaving that off. All things being equal, I'd favour omitting the the suffix.

**Comment by jeromekelleher** [comment]
Total agree with moving away from the ``source`` and ``dest``. I'm not sure about ``parent`` and ``child`` though in terms of migration - this makes me think of trees and a genealogical releationship rather than movements of individuals. I guess we'd need to figure out what the "birth-death" process for demes is first though, so we can nail down what an ``ancestor`` deme is?

**Comment by grahamgower** [comment]
(Using forwards-time language)

Are you suggesting that the language should reflect the process of migration, not migration + leaving offspring? I.e. the edge case of "a migrant is sampled in the destination deme, but leaves no offspring" should neatly fit the language also?

**Comment by grahamgower** [comment]
If you want to stick with forwards-time language, how about something like `egress` / `ingress`. Or perhaps we can find some non-English words that work better?

**Comment by jeromekelleher** [comment]
What about ``from`` and ``to``, under the strictly forwards-time interpretation? This is super-clear and simple, so long as we're not trying to be bi-time-directional.

**Comment by grahamgower** [comment]
I'm happy with that. But `from` is a Python keyword, so outside of the yaml we'd end up using `from_` in practice.

**Comment by jeromekelleher** [comment]
Yes, good call.

**Comment by apragsdale** [comment]
I suggested `parental_deme` and `child_deme` for the from/to language because individuals have parents who were born in some deme (with their children born in some perhaps different deme after migration), and figured the parent/child language is unambiguous whichever direction of time you look. But I guess that's also used to describe genealogical relationships.

If source/dest is confusing, I think from/to and egress/ingress will be similarly confusing. They're just synonyms, and don't really make it clear on their own if we are talking about individuals moving forward in time or lineages backward in time. If we are clear in the documentation that migration is of individuals forward in time, source and destination could still be fine in the end?

**Comment by grahamgower** [comment]
We still use `source` and `dest`. We've definitively decided to use forwards-time conventions now, so these should be unambiguous. So to be honest, I don't prefer any of the other terms we've discussed. Any further comments here, or should we just stick with `source` and `dest`?

**Comment by jeromekelleher** [comment]
I'm ok with that - but these will be in the opposite sense of msprime, right? I think some confusion is unevitable, and at least this confusion would be easily stated.

**Comment by grahamgower** [comment]
Yeah, sorry about that. I suspect the confusion will be maximal in msprime, when it supports the demes format directly.

**Comment by jeromekelleher** [comment]
> Yeah, sorry about that. I suspect the confusion will be maximal in msprime, when it supports the demes format directly.

:shrug: Hard to know whether it would be less confusing if we choose two different words arbitrarily. At least it's easy to remember that we set ``source=dest`` and ``dest=source`` when going back and forth between the two.
