### ISSUE TITLE
API for epochs: remove Deme.add_epoch()?

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#106]
Defining epochs in the python API is a little bit inconsistent, and potentially confusing.

 * Firstly, we have the following construction methods on a DemeGraph: `deme()`, `pulse()`, `migration()`, but then we have `Deme.add_epoch()`. So the naming is inconsistent. We *could* rename it to `epoch()`, so one would do `g.deme("A", ...); g["A"].epoch(...)`, but...
 * The `add_epoch()` method currently requires the deme to already have at least one epoch defined. Naturally, an epoch is inserted when a deme is created with `deme()`. But by default this epoch spans the life time of the deme, so no new epochs can be added anyway.
 * So actually, it tends to not be useful/necessary to call the `add_epoch()` method at all. `DemeGraph.deme()` in fact accepts an `epochs` parameter which is a list of `Epoch`, and while this is also inconsistent with the other API construction methods, it provides much needed flexibility and convenience (e.g. see usage in `demes.loads()`).

So, is it possible to fix `add_epoch()` to make it useful and consistent (and perhaps remove the `epochs` arg to the `deme()` method), or should we just remove `add_epoch()`? I think making `add_epoch()` useful would be hard work though, because I think that `deme()` inserting a single epoch spanning the whole lifetime is very sensible (because maybe no more epochs get added), and so `add_epoch()` would thus need to accept non-temporally-ordered epochs which may also overlap previously added epochs.

**Comment by apragsdale** [comment]
This might be quite similar to #97, where it's a nice idea for dynamically or incrementally building a demography, but ends up confusing users and cluttering the code. We could just remove it or make it not visible in the API, and require users to define every `epoch` of a deme in one go when defining the deme.

I think it was a useful to see how that incremental type of demography construction could go, but in the end it's perhaps unnecessary and ends up cluttering the code with multiple ways of defining deme epochs.

**Comment by apragsdale** [comment]
Closed by #110
