### ISSUE TITLE
Replacing start_time and end_time language for epochs/events

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#2]
If we could use terms that are agnostic to the direction of simulation, that should help to avoid confusion. @apragsdale pointed out that **now** is a very natural reference point, so maybe using language with regard to this reference is worth considering? E.g. ancient/recent, old/young, former/latter.

Does this work though? Given terms `A` and `B`, for more ancient and more recent respectively, we still have a basic disagreement with forward simulators (where A < B) and backward simulators (where A > B).

**Comment by apragsdale** [comment]
Yes, agreed. something like recent/past or along the lines you suggested would be nice. That could help some with the conversion between forward and backward time, I think? We'd need a flag for the flow of time, but then it just is a matter of recalculating times and swapping some `<` and `>` verifications for orders of events.

I've got a branch where I've started changing some attribute names (and also getting a better grasp on how it all works as I'm playing around with it). I can open a PR with some of these suggested naming changes.

**Comment by grahamgower** [comment]
Entropy related terminology would work without **now** as the reference point: time of `low entropy` / `high entropy`. I guess this just changes the reference point to the big bang. Here it's probably more natural to have `time_high_entropy > time_low_entropy`.

I am a little concerned that if we have a flag for the flow of time, this would increase complexity when attempting to validate a demography. But I'm happy to be wrong here.

> I've got a branch where I've started changing some attribute names (and also getting a better grasp on how it all works as I'm playing around with it). I can open a PR with some of these suggested naming changes.

Awesome! I'm about 80% through adding a bunch of docstrings, so we'll probably have some conflicts. I can integrate your PR first though, if that's easier.

**Comment by apragsdale** [comment]
I'd say go ahead with getting the docstrings in. I'm still doing some exploring and you're changes will probably end up being ready before mine.

**Comment by jeromekelleher** [comment]
> I am a little concerned that if we have a flag for the flow of time, this would increase complexity when attempting to validate a demography. But I'm happy to be wrong here.

I'm a bit worried about his too, tbh. I worry that we're doing to end up with very abstract language if we try to be this general. I would rather do one direction well, than two directions not quite so well.

What's the advantage you see from having two directions for time @apragsdale?

**Comment by grahamgower** [comment]
We could support two directions for time at a high level (e.g. yaml file), which is always converted into a single time direction for the low-level where we do validation.

**Comment by jeromekelleher** [comment]
This is a fundamental issue, so I've opened #11 to track it.

**Comment by grahamgower** [comment]
We're still using `start_time` and `end_time`. We've definitively decided on forwards-time conventions now, so the terms are unambiguous. Are we ok with freezing on these terms?

**Comment by jeromekelleher** [comment]
OK by me.
