### ISSUE TITLE
time_units and generation_time attributes

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#20]
If `time_units != "generations"`, then it seems natural to have the value of `generations` in the units given by `time_units`. The only hiccup is when `time_units == "generations"`: what then are the units for `generation_time`? I suggest we have `generation_time=None` in this case. This means we can always convert into generations, but if a model is given in units of generations, we can't convert away. Does anyone see problems with this?

I think the semantics to convert into generations will be as simple as: if time_units != "generations", then divide all times and migration rates by the value of `generation_time`. We can provide a convenience function for this. So the `time_units` attribute will mostly be for human readability of the model.

**Comment by jeromekelleher** [comment]
Seems sensible to me. I think humans will like to be able to state models using units like "kya", and it will make it easier for them to spot mistakes.

**Comment by apragsdale** [comment]
Yeah, this is sensible to me -- have `generation_time` as an optional entry in the YAML file, but if `time_units` are not in generations, then we raise an error if `generation_time` is `None`. We'll probably need to come up with a list of acceptable time units (generations, years, kya, days).

**Comment by grahamgower** [comment]
The semantics ended up being slightly different, but I think this is resolved now after #32.
