### ISSUE TITLE
add functions for exporting to fwdpy11, moments, msprime, etc

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#23]
While these are things that we (and users) will really want, we don't want `demes` to explicitly depend on external packages. But it will be very useful to include them here while `demes` is being developed, at least for testing purposes, until they find a better home. Perhaps for now we just make an "export" folder and chuck scripts in there?

**Comment by apragsdale** [comment]
Totally agree - we don't want to have to depend on msprime or any specific simulation engine. Eventually, the methods that translate `demes` to `msprime` or `fwdpy1` or `dadi` or whatever should live within the those simulation engines, but providing examples to export will still be really useful. An "export" folder makes sense to me for now.

**Comment by molpopgen** [comment]
Totally agree.

**Comment by jeromekelleher** [comment]
Sounds good. We should make a note in there that the directory is temporary and should be deleted at some point (stuff has a habit of sticking around and confusing people!)

**Comment by grahamgower** [comment]
I've now merged a `demes.convert` submodule for this as part of #28, which includes conversion functions to and from msprime. To test it, I added thin wrappers around this for stpopsim, and then converted all stdpopsim models back and forth. Probably there are edge cases lurking, but it seems to work ok. More tests are needed. You can see the output for a specific stdpopsim model like this:
```
$ python demes/convert/stdpopsim_.py HomSap OutOfAfrica_3G09
description: |-
  The three population Out-of-Africa model from Gutenkunst et al. 2009.
  It describes the ancestral human population in Africa, the out of Africa
  event, and the subsequent European-Asian population split.
  Model parameters are the maximum likelihood values of the
  various parameters given in Table 1 of Gutenkunst et al.
time_units: generations
doi: 'Gutenkunst et al., 2009: https://doi.org/10.1371/journal.pgen.1000695'
demes:
  YRI:
    epochs:
    - end_time: 8800.0
      initial_size: 7300.0
    - end_time: 0
      initial_size: 12300.0
  CEU:
    ancestors: YRI
    start_time: 5600.0
    epochs:
    - end_time: 848.0
      initial_size: 2100.0
    - end_time: 0
      initial_size: 1000.0
      final_size: 29725.343546388514
  CHB:
    ancestors: CEU
    start_time: 848.0
    initial_size: 510.0
    final_size: 54090.331077946525
migrations:
  symmetric:
  - demes: YRI, CEU
    rate: 0.00025
    end_time: 848.0
  - demes: YRI, CEU
    rate: 3e-05
    start_time: 848.0
  - demes: YRI, CHB
    rate: 1.9e-05
  - demes: CEU, CHB
    rate: 9.6e-05

```

**Comment by grahamgower** [comment]
We have 2 out of 3 mentioned in the title, so I'm going to close this and open a follow-up issue for fwdpy11.
