### ISSUE TITLE
How to do the YAML round trip entirely w/strictyaml?

### ISSUE THREAD

**Issue by molpopgen** [grahamgower/demes#3]
I'm having trouble figuring out how to do a complete round trip through a YAML file entirely in `strictyaml`.  The built-in `yaml` "just works", though.

The issue is that the output generated by this script contains all the `!!float` tags, which get read back in by anything I've used from `strictyaml`.

Example:

```py
import demes.examples
import strictyaml
import yaml

ooa = demes.examples.gutenkunst_ooa()
y = strictyaml.YAML(ooa.asdict())

with open("ooa.yml", "w") as f:
    f.write(y.as_yaml())

with open("ooa.yml", "r") as f:
    l = f.read()
    yy = strictyaml.as_document(l)

x = strictyaml.load(yy.as_yaml())

# This gives  what we want, though
with open("ooa.yml", "r") as f:
    yyy = yaml.load(f)

assert ooa.asdict() == yyy, "Sad face!"
```

**Comment by grahamgower** [comment]
I don't think strictyaml will do what you want without specifying a schema (like in `demes/script.py`). But the lack of reference documentation for strictyaml makes it hard to figure this stuff out (e.g. what does `strictyaml.YAML()` actually do here?). Also, there's no yaml package included with cpython, so you must have some other yaml package installed.

**Comment by molpopgen** [comment]
I seem to have PyYaml installed.  I'm trying to start with a yaml file, read it in, and create a deme graph from it's contents.  I want to get a sense of what that'll look like, and maybe build a fwdpy11 model from the input, too.

**Comment by molpopgen** [comment]
Cool, I see that `scripts.py` is doing this part.

**Comment by grahamgower** [comment]
Yep, and the relevant bits from script.py are imported into the main `demes` namespace. So you should be able to do something like:
```python
import demes
import demes.examples
ooa = demes.examples.gutenkunst_ooa()
demes.dump(ooa, "ooa.yml")
```

**Comment by grahamgower** [comment]
I think this is resolved, so I'm going to close. Reopen if you disagree.
