### ISSUE TITLE
migration rate units?

### ISSUE THREAD

**Issue by molpopgen** [grahamgower/demes#30]
@apragsdale and I noticed that the units for migration rates are implicitly in generations.  Is this what we want?  If the model is scaled with times in years, then should the migration rates be per year as well?  I think that the per generation rate is sensible, but we need to make clear what we're doing in any case.

**Comment by grahamgower** [comment]
Eeek! I'd assumed they were implicitly in the same units as the rest of the times! Personally, I think using the same units is more consistent and less confusing, but I can see how it would trip people up. This definitely needs clear and obvious documentation.

Presumably `selfing_rate` and `cloning_rate` should follow whatever we do for migration rate?

**Comment by molpopgen** [comment]
Yeah, so that's the implictness coming back to bite us.  When @apragsdale wrote the YAML files for the Browning and Gutenkunst models, I think that he copied the migration rates from those papers, and so they're the per-generation ancestry proportions from each parental population.

The selfing/cloning rates are a good point, too.  They definitely need units, and I'm hesitant to go down a road of everything having its own `unit` attribute.

**Comment by jeromekelleher** [comment]
This is tricky - I agree with @grahamgower that everything should be in the same units, with if we're using things like ``time_units="kya"``, then having to express rates in units of ``1/kya`` would be tedious and error prone.

How about having ``time_units`` and ``rate_units``? Often rates are most naturally expressed in generations, so we want to enable that.

**Comment by grahamgower** [comment]
I've changed my mind on this. #32 gives a conversion function that only converts times, ignoring rates. Probably times are special. I'm coming around to the idea that generations are the natural units for everything, and giving times in units of years (or thousands of years) is a convenience for users. This convenience evaporates if they must then convert their rates which are almost certainly already "per generation" (e.g. from a publication, or to match conventions of other software).

**Comment by molpopgen** [comment]
@apragsdale and I have gone back and forth in this, too, via slack.  I agree that migration rates in kya or whatnot seems very unnatural for the most likely use cases.

**Comment by apragsdale** [comment]
I am coming to agree more and more with this, that it makes sense to allow flexibility in how time units are given, along with specifying generation time if time units are not generations. But to me, migration rates and other rates like that are most natural in units of per-generation, and I'd be happy with avoiding the whole business of expecting users to recalculate rates in non-per-generation units.

**Comment by jeromekelleher** [comment]
So rates are always per generation?

**Comment by grahamgower** [comment]
> So rates are always per generation?

Lets go with that, unless there's a compelling reason to change it.
