### ISSUE TITLE
in_generations() is not rescaling migration rates

### ISSUE THREAD

**Issue by apragsdale** [grahamgower/demes#37]
Looks like the `in_generations()` function does not rescale migration rates (i.e. converting from years to generations does not change the migration rates from units of per-year to per-generation).

Should be a quick fix - I'll have a go at it (unless this was the intended behavior?)

**Comment by grahamgower** [comment]
I thought we decided that migration rates should always be per generation? #30

**Comment by molpopgen** [comment]
I'd like to further propose that the rate be per "gamete", per generation.  In some areas, like quantitative genetics, mutation rates are often written as per offspring, and thus differ by a factor of the ploidy.  I think we should have the "strict pop-gen" definition here.

**Comment by apragsdale** [comment]
Ok, yes now I vaguely remember we had agreed that all rates should be per-generation. And I also agree that that should be "per gamete per generation", like you suggested Kevin.

If that's the case, then I don't think we need to fix the `in_generations` code like the PR I opened. But some of our examples haven't been updated to be in units of per generation instead of per year, which is what threw me off. (The `demes.examples.gutenkunst_ooa()` model is still in per year, so I should fix those.)
