### ISSUE TITLE
Add docstrings that describe current behaviour

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#4]
`demes` clearly needs some minimal documentation. "Minimal", only because everything is likely to change.

**Comment by molpopgen** [comment]
I can work up some examples based on my playing around. We can also `literalinclude` line ranges from `demes/examples.py`. That sort of thing should be enough for now.

**Comment by grahamgower** [comment]
I addes some docstrings in #5. @molpopgen, it would be great if you could insert a couple of examples too!

**Comment by grahamgower** [comment]
I think we have most of the docstrings in place now. And the formal behaviour will be described elsewhere (#56, #57, #59).
