### ISSUE TITLE
triage all our examples so that we don't include incorrect models

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#41]
I've been especially slack with checking correctness of the example models... Sorry!

**Comment by apragsdale** [comment]
I'll look through these today, at least for correct units of migration rates. I think that will end up being the main issues we find.

**Comment by grahamgower** [comment]
Great, thanks! We have both `examples/` the folder, and `demes/examples.py` (it might be nice to deduplicate these at some point too).

**Comment by apragsdale** [comment]
Yeah, that's true we have the duplicates. Though the `examples/` directory stores the yaml descriptions/files for those demographic models, and `demes/examples.py` has those same models implemented from within the Python API. We should at least be testing for equality between them, which I _think_ some of the tests now are doing, but I'd need to double check.
