### ISSUE TITLE
setup somewhere for the docs to live

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#42]
Probably github pages. Should be easy to transfer to the popsim-consortium if/when that happens.

**Comment by apragsdale** [comment]
Yeah, that makes sense. And I think we should start at least drafting up documentation -- I've found some time/motivation recently to dive back into this, so I can work on getting the docs started once the moments conversion is finalized (which should be soon).

Once we have some docs and the conversion for msprime/stdpopsim/moments/fwdpy11 all finished, I wouldn't mind putting together a presentation of this project the stdpopsim call as well. I think with the recent resurgence in interest in stdpopsim (with like 50 people on the last call), that should serve as advertisement for this project and hopefully be convincing for people to adopt it in their own work, whether in stdpopsim or beyond.

**Comment by grahamgower** [comment]
I've created a `demes-docs` github page: https://grahamgower.github.io/demes-docs/main/
This will be auto updated, and also hold PR docs previews, like what @benjeffery did for tskit and msprime. It should be trivial to move this to another repository in the future.

**Comment by benjeffery** [comment]
I'll let you know when I do the next parts of this - which is to prune old doc versions for closed PRs and to add a verison picker to the site.

**Comment by grahamgower** [comment]
Perfect! Thanks @benjeffery!
