### ISSUE TITLE
add minimal CLI to load/validate a yaml file

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#50]
Loading a yaml with `demes.load()` already does the validation, so I guess this just needs a wrapper and an `entry_points` glue in the `setup.cfg`/`setup.py`. This will be useful for the docs, where we can include examples of erroneous models, and show the error messages. (And it will help us check that the error messages are useful).

**Comment by jeromekelleher** [comment]
I recommend using [click](https://click.palletsprojects.com/en/7.x/) - it's awesome. I've resolved to never write another argparse interface after trying it out!

**Comment by molpopgen** [comment]
Click has never clicked for me!

**Comment by grahamgower** [comment]
I'll keep it in mind. But I think any argument parsing would be overkill for this program.
