### ISSUE TITLE
add licensing/copyright

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#6]
MIT or similar.

**Comment by jeromekelleher** [comment]
Can you give the motivation for choosing the ISC license please @grahamgower, so we have a record?

**Comment by grahamgower** [comment]
Sure. It's basically the same as the MIT or 3-clause BSD licenses, but it uses fewer words. Less is more.

**Comment by jeromekelleher** [comment]
MIT is better known, though - people may need to look this one up to see what it means.

**Comment by grahamgower** [comment]
If you feel really strongly about it, it is an easy change...

**Comment by jeromekelleher** [comment]
I don't feel strongly about it, no. @molpopgen, what do you think?

**Comment by molpopgen** [comment]
I'll have to read it first.  I won't be at a computer much today, though.

**Comment by molpopgen** [comment]
Read it on my phone.  Seems fine to me.

**Comment by jeromekelleher** [comment]
OK, let's leave it then.
