### ISSUE TITLE
improve test coverage

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#68]
In particular, there are a bunch of code paths in `demes/demes.py` that we should try to hit.

**Comment by apragsdale** [comment]
Yes, good call. I'll take a pass at this this afternoon. Should we set up a Codecov check for this repo, as well?

**Comment by grahamgower** [comment]
I'm going to reopen this, because I think there's still a bunch left to do. I'll work on it a bit today too. Agreed that we should set up Codecov.
