### ISSUE TITLE
Claim the demes name from pypi

### ISSUE THREAD

**Issue by apragsdale** [grahamgower/demes#78]
From today's call, should we squat the `demes` name for the upcoming release? I haven't done this before (last time I tried, the software name I wanted was already taken long ago)..

**Comment by grahamgower** [comment]
I'm not sure how this is done. It it a requirement to upload a release with `twine`?

**Comment by jeromekelleher** [comment]
Yes - the simplest thing to do is to create an empty package. To be honest, it might be simplest to just tag what we have today as 0.1.0a1 and upload that with twine. @grahamgower - are you happy to be the package owner on pypi? I'm happy to be an admin as well (you can add me on the pypi interface).

**Comment by grahamgower** [comment]
Ok, I'll see if I can figure it out. Do I first have to push a tag to the repository?

**Comment by jeromekelleher** [comment]
Creating a release using the GitHub UI is the simplest approach. Then when you git pull, setuptools_scm will see the tag and set the version accordingly.

**Comment by grahamgower** [comment]
Done! https://pypi.org/project/demes/

**Comment by apragsdale** [comment]
Nice work!! That was quick. Now we can all sleep at night knowing we won't get scooped :)
