### ISSUE TITLE
allow non-exponential population size functions?

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#8]
@molpopgen pointed out that the coalescent-simulator type exponential growth of population sizes is not the only reasonable choice. https://github.com/grahamgower/demes/pull/5#discussion_r456954694

Do we want to support an additional keyword for the type of growth?

**Comment by jeromekelleher** [comment]
Yes, I think we want to keep the door open on this one. Maybe we can say it defaults to exponential growth, but we imagine having other possibilities in the future.

**Comment by grahamgower** [comment]
The `Epoch` class has a `size_function` attribute, as of #17.
