### ISSUE TITLE
delete `demes/examples.py` API examples in favour of yaml `examples/` folder

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#88]
We currently have examples using the Python API in `demes/examples.py` (importable via `import demes.examples`), and `yaml` examples under the `examples/` folder. Should we deduplicate this? If we want to keep both, maybe we want to put them side-by-side in the docs?

**Comment by jeromekelleher** [comment]
What's the use-case for teaching people the Python API? So they can dynamically construct their own models, and avoid writing out yaml text?

**Comment by grahamgower** [comment]
That might be the most common use case. But learning the API is also a first step towards understanding what's in a `demes.DemeGraph`, what its attributes are, etc. So folks are then able to use this in their own demographic-model-consuming software (or convert to a different format).

**Comment by jeromekelleher** [comment]
I'm not sure it's good idea to have ``demes.examples`` importable as a package - I don't really want to think about the horrible ways in which users might abuse this and what mess we might need to clean up. I'd say keeping the documentation focused on the audience and having specific examples inlined in the documentation that are specifically designed to illustrate particular parts of the API.

The Yaml-user (people writing models) documentation and Python API documentation (developers dynamically creating demes models) should be quite separate I think, as we need to assume much less Python knowledge for the former.

**Comment by grahamgower** [comment]
Sounds good! I think I wrote the `demes/examples.py` code to test out if the API made sense. We can probably `dump()` the Jacobs et al. model to a yaml file in the `examples/` folder (I think this is the only one we don't already have yaml for), and delete the python code.
