### ISSUE TITLE
make demes pip-installable

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#9]
Needs a `setup.py` file, or similar. Is there a canonical way of doing this yet?

**Comment by jeromekelleher** [comment]
Yes, needs setup.py. But, let's use setup.cfg and a minimal setup.py using setuptools_scm like [this repo](https://github.com/pystatgen/sgkit)

**Comment by grahamgower** [comment]
Thanks @jeromekelleher. I copied as few things as I could, and it seems to work. Setuptools stuff makes me nervous though---I bet this breaks without sensible error messages on a range of just-old-enough systems.
