### ISSUE TITLE
use more keyword-only arguments

### ISSUE THREAD

**Issue by grahamgower** [grahamgower/demes#92]
While keyword-only args can sometimes be annoying (it's more typing), it makes it impossible to provide arguments in the wrong order. It's also produces much easier to read code (such as tests), as the reader doesn't have to know the arg order or look up the arg order.

So I think we should change to `kw_only=True` for the attr's classes. And the methods on `DemeGraph` should be mostly keyword-only.

**Comment by jeromekelleher** [comment]
I agree with this - it gives much more flexibility in API design long-term too.
